server:
  port: 8080

spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    userName: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

build:
  version: "1.0"

accounts:
  message: "Welcome to java learners accounts service"
  contactDetails:
    name: "chiranjeevi"
    email: "chiranjeevi.com"
  onCallSupport:
    - (555) 555-4444
    - (555) 565-4646