server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "4.0"

cards:
  message: "Welcome to java learners cards service"
  contactDetails:
    name: "John cena"
    email: "youcant@seeme.com"
  onCallSupport:
    - (555) 555-4444
    - (555) 565-4646