server:
  port: 8090

spring:
  application:
    name: Loans

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    userName: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

build:
  version: "4.0"

loans:
  message: "Welcome to java learners loans service"
  contactDetails:
    name: "John cena"
    email: "youcant@seeme.com"
  onCallSupport:
    - (555) 555-4444
    - (555) 565-4646